/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:77f649e6-85bc-42ce-b2c0-0d2e9525e62c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cXpmlWYzC",
    "aws_user_pools_web_client_id": "45cv1mipkejtaosb80s430jml6",
    "oauth": {}
};


export default awsmobile;
